name: 'Release downloader'
description: 'Download a release'
inputs:
  repository:
    description: Repository containing release
    required: false
    default: ${{ github.repository }}
  destination:
    description: Destination
    required: false
    default: ${{ github.workspace }}
  version:
    description: Version to retrieve (defaults to latest)
    required: false
    default: ''
  os:
    description: OS to favor (defaults to current)
    required: false
    default: ''
  os-pattern:
    description: OS pattern to filter (defaults to calculating based on os)
    required: false
    default: ''
  arch:
    description: Architecture to favor (defaults to current)
    required: false
    default: ''
  arch-pattern:
    description: Architecture pattern to filter (defaults to calculating based on arch)
    required: false
    default: ''
  file-re:
    description: File pattern (in case os/arch aren't enough to select)
    required: false
    default: ''
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  debug:
    description: Trace action
    required: false
    default: ''
outputs:
  url:
    description: Downloaded artifact URL
    value: ${{ steps.action.outputs.url }}
  path:
    description: Path to file on disk
    value: ${{ steps.action.outputs.path }}
runs:
  using: "composite"
  steps:
  - name: Run downloader
    id: action
    continue-on-error: false
    shell: bash
    run: |
      : Run downloader
      $GITHUB_ACTION_PATH/gh-release-downloader
    working-directory: ${{ inputs.checkout_path }}
    env:
      GH_TOKEN: ${{ inputs.token }}
      repo: ${{ inputs.repository }}
      destination: ${{ inputs.destination }}
      version: ${{ inputs.version }}
      os: ${{ inputs.os }}
      os_re: ${{ inputs.os-pattern }}
      arch: ${{ inputs.arch }}
      arch_re: ${{ inputs.arch-pattern }}
      file_re: ${{ inputs.file-re }}
      debug: ${{ inputs.debug }}
